### ISSUE TITLE
Using another LLM

### ISSUE THREAD

**Issue by lhkhiem28** [XiaoxinHe/G-Retriever#1]
Hi. Thanks for an interesting repo

I have a question regarding the usage of LLMs. Is the repo agnostic to any LLMs or only made for llama? More specifically, does the code work correctly if I use another LLM, such as Mixtral by replacing “llama2/llama2_7b_chat_hf” with “mistralai/Mixtral-8x7B-Instruct-v0.1”? If not, how can I change the code for using another LLM? Thanks.

**Comment by XiaoxinHe** [comment]
Hi,

Thank you for your interest in our work.

Unfortunately, it is not agnostic to any LLMs and supports only decoder-only LLMs. I haven't tested it on other decoder-only models except llama, but I believe other decoder-only models should work fine. Some minor modifications will be needed, such as changing the BOS (beginning of sentence), EOS, and padding tokens in either the file "src/model/graph_llm.py" (if using our G-retriever) or "src/model/llm.py" (if you are considering the baseline LLM).

Let me know if you need further help. Thanks!

**Comment by lhkhiem28** [comment]
Hi @XiaoxinHe . Thank you very much for your answer.

I am curious about the difference between `Llama-*-hf` and `Llama-*-chat-hf` in your project. Could you explain why you use `Llama-*-chat-hf` for Inference-Only configuration, but `Llama-*-hf` for Prompt Tuning configuration? Why we don't use `Llama-*-chat-hf` for Prompt Tuning?
I don’t find this information in the paper.
Thanks!

**Comment by XiaoxinHe** [comment]
Hi,

I used llama-chat-hf for an inference-only configuration because it is more chat-friendly compared to the llama-hf version, which can better understand the given task and instruction. For example, given the question "Argument 1: Women should not be in combat. Argument 2: Women and men have the same rights. Question: Do argument 1 and argument 2 support or counter each other? Answer in one word in the form of 'support' or 'counter'." I would like the model to answer the question and give exactly 'support' or 'counter' as an answer. Even though the instruction is carefully designed, llama-hf might fail to follow the instructions in some cases, leading to difficulties in evaluating the answer. Therefore, we prefer to use llama-chat-hf for the inference-only configuration.

For the prompt-tuning configuration, the model, or the soft prompt, will be trained. In these cases, the model is trained to answer following a certain format due to gradient back-propagation, such as always answering with 'support' or 'counter'. In this case, using either llama-chat-hf or llama-hf would make no significant difference.

We will explain this in our next manuscript. Thanks for your question.

**Comment by lhkhiem28** [comment]
Hi @XiaoxinHe . Thank you so much for your answers.

I am trying to use another LLM rather than Llama and I am looking at special tokens of those models. 

As I know (I am not really sure), Llama's eos token is `</s>`, however, you are using `[/s]` in your code (e.g. "src/model/llm.py"). Can you confirm that the eos token of Lllama is [/s]? If not, does this mismatch affect the model's behavior?

Thank you!

**Comment by XiaoxinHe** [comment]
Yes, you are right! The EOS token should be `</s>`. I will rerun the codes to see if it affects the model's behavior. Thanks!

**Comment by lhkhiem28** [comment]
Hi @XiaoxinHe 

Looking forward to your updated results.

Btw, can you share how many hours are needed for training G-retriever 7B (with and without LoRA) with batch size 4 on 2 A100-80G GPUs (as the setting you mentioned in the paper)?

Why didn't you use a larger batch size?

Thank you!

**Comment by XiaoxinHe** [comment]
Hi,

It takes around 1 to 1.5 hours to train G-retriever 7B (with and without LoRA) with a batch size of 4 on 2 A100-80G GPUs. I didn't use a larger batch size since my GPU servers are shared, and sometimes it's necessary to leave some space for other users. Actually, you can use a larger batch size as long as it fits into your memory.

It takes some time to rerun the experiments. I will keep you updated on that. Thanks!

**Comment by lingvisa** [comment]
@XiaoxinHe Any update on the correction of EOS token? Just curious to know and thank you!

**Comment by XiaoxinHe** [comment]
Hi,

The latest code has fixed the issue with the EOS token, and all the experiments have been rerun. Please refer to our latest manuscript at https://arxiv.org/pdf/2402.07630. Thank you!
