### ISSUE TITLE
Do expla_graphs and scene_graphs datasets need retrieval?

### ISSUE THREAD

**Issue by quqxui** [XiaoxinHe/G-Retriever#22]
Hi,
Your job sounds interesting. I would like to know, for the datasets expla_graphs and scene_graphs, when given a question, do I need to retrieve specific subgraphs, or can I directly obtain the corresponding graph?

Thanks.

**Comment by XiaoxinHe** [comment]
Hi,

Thank you for your interest in our work. Yes, for a given question, you need to retrieve specific subgraphs. The retrieved subgraph will vary depending on the query. You can refer to our data processing steps here: https://github.com/XiaoxinHe/G-Retriever/blob/6de1818da77645c61f5d7fb290d47ea070e66885/src/dataset/webqsp.py#L75


Additionally, since expla_graphs is a dataset of small graphs, we skip retrieval and use the entire graph instead of a subgraph. For scene_graphs and web_qsp, we use PCST-based retrieval to obtain the subgraphs.
