### ISSUE TITLE
About scene_graphs

### ISSUE THREAD

**Issue by HuieL** [XiaoxinHe/G-Retriever#5]
I just found there are only 74,942 graphs in  `train_sceneGraphs.json`  and 10,696 graphs in `val_sceneGraphs.json`, resulting total 85,638 graphs in scene_graphs but not 100,000 reported. Only  `train_sceneGraphs.json` is used in `src.dataset.preprocess.scene_graphs` but split is for 100,000 samples.

**Comment by XiaoxinHe** [comment]
Hi,

Thank you for your question. This is because for one image, there might be multiple questions. For example, for the image with image_id=4, there are 5 corresponding questions. The size of the dataset is determined by the number of questions, not the number of images.


<img width="808" alt="Screenshot 2024-04-15 at 11 48 52 AM" src="https://github.com/XiaoxinHe/G-Retriever/assets/48676630/364276a9-7479-4bc5-99af-df747de0a6aa">
