### ISSUE TITLE
Train on new dataset

### ISSUE THREAD

**Issue by chaymabh** [XiaoxinHe/G-Retriever#8]
Hello, thank you for the great work. I am attempting to fine-tune the G_retriever framework on a custom question-answering dataset using a GPU with 16GB of memory. However, I encounter out-of-memory errors during the training process.
Is there a recommended minimum GPU memory requirement for fine-tuning G_retriever on 14,3 MB dataset?
Are there additional optimization strategies or code modifications that could enable effective fine-tuning on a 16GB GPU?

**Comment by XiaoxinHe** [comment]
Hi, thank you for your interest in our work. Regarding your concern about GPU memory, I am afraid that a single 16GB GPU might not be sufficient for training, finetuning, or prompt tuning; however, inference should be fine. This is because, aside from the model parameters themselves, there will be numerous hidden states cached during training, which will consume a significant amount of memory. Based on my experience, to train Llama2-7B, you will need at least two 16GB GPUs. You can adjust the number of GPUs and their memory by modifying the code here: https://github.com/XiaoxinHe/G-Retriever/blob/a4baacdd5c2d12460b3881eb63b9b376e4ea18c3/src/model/graph_llm.py#L34

Alternatively, you could consider combining G-Retriever with other efficient finetuning methods, such as quantization.
